appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: dmz0Ucy6LAH3ZU+CewFkNjA3It36Jd7qIaTsZKTt6MNFIXaFUTA293r288uN+2OXxfbf7TkV7Mi2OudQjdmaPpHSFqguxZAh9mWXN0+LikpLeEhuvZ0zxPrSVViFJSx6QJ1gBpst6lW3hBPECFxuC6GeO3B48kLSX17tff3POODqtnX4jH4nSqowuYMgwWDHHqQTbkamh9ttPL8TUYhglpa9zmB/YurnetrnarN0jp4z3qN4yQw71tybWhidFMKYs5re48NlktYGHc006Ai60xwOsghKNeaK8g+lp7d2OpyEqbMVh7ksQ6lUNCbK3u5HziSOHZE/Y6fG8lo4aIXoYC432neyB8HDN5hm5JuSGv+HMTwYCTFFiHM5ZIlXAZK66/1kcyLFKezYkeyyjXQSd2tfZct/9DBUCjYQj2wemYD98dhBT9ocW4Ey6o0XsOoQ8P7v7scdVBwPrk+lofWDuGoyyfb5lPchBdsLkX5L0KDzh5bPAhUQbHWDFuA+Y4CNIokF888NFAfKZPHXkzGJ0Eyn1ZE/V3S79FyYy0k20GnkAXgSjLehYXIEGTeuZZyq52U8vGnUuerI3Mt8Xz46zyYlAQbIN/Q6siyHKOMjTJaVVrlDfKRiZhk8fWL+XcFRPMwvf3mUR9NmMejaZQxkAAbYSgvVLc2XNcLTZKQa0/U=
